"""The NSE stock universe Delta knows about: symbol, display name and sector."""

# symbol -> (display name, sector)
STOCKS = {
    # Banking & Finance
    "HDFCBANK.NS": ("HDFC Bank", "Banking & Finance"),
    "ICICIBANK.NS": ("ICICI Bank", "Banking & Finance"),
    "SBIN.NS": ("State Bank of India", "Banking & Finance"),
    "KOTAKBANK.NS": ("Kotak Mahindra Bank", "Banking & Finance"),
    "AXISBANK.NS": ("Axis Bank", "Banking & Finance"),
    "INDUSINDBK.NS": ("IndusInd Bank", "Banking & Finance"),
    "PNB.NS": ("Punjab National Bank", "Banking & Finance"),
    "BANKBARODA.NS": ("Bank of Baroda", "Banking & Finance"),
    "CANBK.NS": ("Canara Bank", "Banking & Finance"),
    "IDFCFIRSTB.NS": ("IDFC First Bank", "Banking & Finance"),
    "FEDERALBNK.NS": ("Federal Bank", "Banking & Finance"),
    "AUBANK.NS": ("AU Small Finance Bank", "Banking & Finance"),
    "YESBANK.NS": ("Yes Bank", "Banking & Finance"),
    "BAJFINANCE.NS": ("Bajaj Finance", "Banking & Finance"),
    "BAJAJFINSV.NS": ("Bajaj Finserv", "Banking & Finance"),
    "JIOFIN.NS": ("Jio Financial Services", "Banking & Finance"),
    "SHRIRAMFIN.NS": ("Shriram Finance", "Banking & Finance"),
    "CHOLAFIN.NS": ("Cholamandalam Finance", "Banking & Finance"),
    "MUTHOOTFIN.NS": ("Muthoot Finance", "Banking & Finance"),
    "SBICARD.NS": ("SBI Cards", "Banking & Finance"),
    "PFC.NS": ("Power Finance Corporation", "Banking & Finance"),
    "RECLTD.NS": ("REC Limited", "Banking & Finance"),
    "IRFC.NS": ("Indian Railway Finance", "Banking & Finance"),
    "LICI.NS": ("LIC of India", "Banking & Finance"),
    "SBILIFE.NS": ("SBI Life Insurance", "Banking & Finance"),
    "HDFCLIFE.NS": ("HDFC Life Insurance", "Banking & Finance"),
    "HDFCAMC.NS": ("HDFC Asset Management", "Banking & Finance"),
    "PAYTM.NS": ("Paytm", "Banking & Finance"),

    # Technology
    "TCS.NS": ("Tata Consultancy Services", "Technology"),
    "INFY.NS": ("Infosys", "Technology"),
    "WIPRO.NS": ("Wipro", "Technology"),
    "HCLTECH.NS": ("HCL Technologies", "Technology"),
    "TECHM.NS": ("Tech Mahindra", "Technology"),
    "PERSISTENT.NS": ("Persistent Systems", "Technology"),
    "COFORGE.NS": ("Coforge", "Technology"),
    "MPHASIS.NS": ("Mphasis", "Technology"),
    "LTTS.NS": ("L&T Technology Services", "Technology"),
    "OFSS.NS": ("Oracle Financial Services", "Technology"),
    "TATAELXSI.NS": ("Tata Elxsi", "Technology"),
    "TATATECH.NS": ("Tata Technologies", "Technology"),
    "KPITTECH.NS": ("KPIT Technologies", "Technology"),
    "CYIENT.NS": ("Cyient", "Technology"),
    "BSOFT.NS": ("Birlasoft", "Technology"),

    # Energy & Industrials
    "RELIANCE.NS": ("Reliance Industries", "Energy & Industrials"),
    "ONGC.NS": ("ONGC", "Energy & Industrials"),
    "NTPC.NS": ("NTPC", "Energy & Industrials"),
    "POWERGRID.NS": ("Power Grid", "Energy & Industrials"),
    "COALINDIA.NS": ("Coal India", "Energy & Industrials"),
    "IOC.NS": ("Indian Oil", "Energy & Industrials"),
    "BPCL.NS": ("Bharat Petroleum", "Energy & Industrials"),
    "HINDPETRO.NS": ("Hindustan Petroleum", "Energy & Industrials"),
    "GAIL.NS": ("GAIL India", "Energy & Industrials"),
    "PETRONET.NS": ("Petronet LNG", "Energy & Industrials"),
    "IGL.NS": ("Indraprastha Gas", "Energy & Industrials"),
    "ADANIENT.NS": ("Adani Enterprises", "Energy & Industrials"),
    "ADANIPOWER.NS": ("Adani Power", "Energy & Industrials"),
    "ADANIGREEN.NS": ("Adani Green Energy", "Energy & Industrials"),
    "ADANIENSOL.NS": ("Adani Energy Solutions", "Energy & Industrials"),
    "TATAPOWER.NS": ("Tata Power", "Energy & Industrials"),
    "JSWENERGY.NS": ("JSW Energy", "Energy & Industrials"),
    "NHPC.NS": ("NHPC", "Energy & Industrials"),
    "SUZLON.NS": ("Suzlon Energy", "Energy & Industrials"),
    "LT.NS": ("Larsen & Toubro", "Energy & Industrials"),
    "SIEMENS.NS": ("Siemens India", "Energy & Industrials"),
    "ABB.NS": ("ABB India", "Energy & Industrials"),
    "BHEL.NS": ("BHEL", "Energy & Industrials"),
    "BEL.NS": ("Bharat Electronics", "Energy & Industrials"),
    "HAL.NS": ("Hindustan Aeronautics", "Energy & Industrials"),
    "CGPOWER.NS": ("CG Power", "Energy & Industrials"),
    "HAVELLS.NS": ("Havells India", "Energy & Industrials"),
    "POLYCAB.NS": ("Polycab India", "Energy & Industrials"),

    # Consumer
    "ITC.NS": ("ITC", "Consumer"),
    "HINDUNILVR.NS": ("Hindustan Unilever", "Consumer"),
    "NESTLEIND.NS": ("Nestle India", "Consumer"),
    "BRITANNIA.NS": ("Britannia Industries", "Consumer"),
    "DABUR.NS": ("Dabur India", "Consumer"),
    "MARICO.NS": ("Marico", "Consumer"),
    "GODREJCP.NS": ("Godrej Consumer Products", "Consumer"),
    "COLPAL.NS": ("Colgate-Palmolive India", "Consumer"),
    "TATACONSUM.NS": ("Tata Consumer Products", "Consumer"),
    "VBL.NS": ("Varun Beverages", "Consumer"),
    "UNITDSPR.NS": ("United Spirits", "Consumer"),
    "UBL.NS": ("United Breweries", "Consumer"),
    "JUBLFOOD.NS": ("Jubilant FoodWorks (Domino's)", "Consumer"),
    "DMART.NS": ("Avenue Supermarts (DMart)", "Consumer"),
    "TRENT.NS": ("Trent (Westside)", "Consumer"),
    "TITAN.NS": ("Titan Company", "Consumer"),
    "KALYANKJIL.NS": ("Kalyan Jewellers", "Consumer"),
    "ASIANPAINT.NS": ("Asian Paints", "Consumer"),
    "BERGEPAINT.NS": ("Berger Paints", "Consumer"),
    "PIDILITIND.NS": ("Pidilite Industries", "Consumer"),
    "VOLTAS.NS": ("Voltas", "Consumer"),
    "BATAINDIA.NS": ("Bata India", "Consumer"),
    "PAGEIND.NS": ("Page Industries (Jockey)", "Consumer"),
    "NYKAA.NS": ("Nykaa", "Consumer"),
    "ETERNAL.NS": ("Eternal (Zomato)", "Consumer"),
    "SWIGGY.NS": ("Swiggy", "Consumer"),

    # Metals & Materials
    "TATASTEEL.NS": ("Tata Steel", "Metals & Materials"),
    "JSWSTEEL.NS": ("JSW Steel", "Metals & Materials"),
    "HINDALCO.NS": ("Hindalco Industries", "Metals & Materials"),
    "VEDL.NS": ("Vedanta", "Metals & Materials"),
    "JINDALSTEL.NS": ("Jindal Steel & Power", "Metals & Materials"),
    "SAIL.NS": ("SAIL", "Metals & Materials"),
    "NMDC.NS": ("NMDC", "Metals & Materials"),
    "NATIONALUM.NS": ("National Aluminium", "Metals & Materials"),
    "HINDZINC.NS": ("Hindustan Zinc", "Metals & Materials"),
    "APLAPOLLO.NS": ("APL Apollo Tubes", "Metals & Materials"),
    "ULTRACEMCO.NS": ("UltraTech Cement", "Metals & Materials"),
    "SHREECEM.NS": ("Shree Cement", "Metals & Materials"),
    "AMBUJACEM.NS": ("Ambuja Cements", "Metals & Materials"),
    "ACC.NS": ("ACC", "Metals & Materials"),
    "DALBHARAT.NS": ("Dalmia Bharat", "Metals & Materials"),
    "JKCEMENT.NS": ("JK Cement", "Metals & Materials"),
    "GRASIM.NS": ("Grasim Industries", "Metals & Materials"),
    "UPL.NS": ("UPL", "Metals & Materials"),
    "PIIND.NS": ("PI Industries", "Metals & Materials"),
    "SRF.NS": ("SRF", "Metals & Materials"),
    "TATACHEM.NS": ("Tata Chemicals", "Metals & Materials"),
    "ASTRAL.NS": ("Astral", "Metals & Materials"),

    # Healthcare
    "SUNPHARMA.NS": ("Sun Pharmaceutical", "Healthcare"),
    "DRREDDY.NS": ("Dr Reddy's Laboratories", "Healthcare"),
    "CIPLA.NS": ("Cipla", "Healthcare"),
    "DIVISLAB.NS": ("Divi's Laboratories", "Healthcare"),
    "APOLLOHOSP.NS": ("Apollo Hospitals", "Healthcare"),
    "LUPIN.NS": ("Lupin", "Healthcare"),
    "AUROPHARMA.NS": ("Aurobindo Pharma", "Healthcare"),
    "TORNTPHARM.NS": ("Torrent Pharmaceuticals", "Healthcare"),
    "ZYDUSLIFE.NS": ("Zydus Lifesciences", "Healthcare"),
    "ALKEM.NS": ("Alkem Laboratories", "Healthcare"),
    "GLENMARK.NS": ("Glenmark Pharmaceuticals", "Healthcare"),
    "BIOCON.NS": ("Biocon", "Healthcare"),
    "MANKIND.NS": ("Mankind Pharma", "Healthcare"),
    "ABBOTINDIA.NS": ("Abbott India", "Healthcare"),
    "IPCALAB.NS": ("Ipca Laboratories", "Healthcare"),
    "LAURUSLABS.NS": ("Laurus Labs", "Healthcare"),
    "FORTIS.NS": ("Fortis Healthcare", "Healthcare"),
    "MAXHEALTH.NS": ("Max Healthcare", "Healthcare"),
    "SYNGENE.NS": ("Syngene International", "Healthcare"),
    "LALPATHLAB.NS": ("Dr Lal PathLabs", "Healthcare"),

    # Auto
    "MARUTI.NS": ("Maruti Suzuki", "Auto"),
    "TMPV.NS": ("Tata Motors Passenger Vehicles", "Auto"),
    "TMCV.NS": ("Tata Motors Commercial Vehicles", "Auto"),
    "M&M.NS": ("Mahindra & Mahindra", "Auto"),
    "BAJAJ-AUTO.NS": ("Bajaj Auto", "Auto"),
    "HEROMOTOCO.NS": ("Hero MotoCorp", "Auto"),
    "EICHERMOT.NS": ("Eicher Motors (Royal Enfield)", "Auto"),
    "TVSMOTOR.NS": ("TVS Motor Company", "Auto"),
    "ASHOKLEY.NS": ("Ashok Leyland", "Auto"),
    "ESCORTS.NS": ("Escorts Kubota", "Auto"),
    "HYUNDAI.NS": ("Hyundai Motor India", "Auto"),
    "OLAELEC.NS": ("Ola Electric", "Auto"),
    "BHARATFORG.NS": ("Bharat Forge", "Auto"),
    "MOTHERSON.NS": ("Samvardhana Motherson", "Auto"),
    "BOSCHLTD.NS": ("Bosch India", "Auto"),
    "MRF.NS": ("MRF", "Auto"),
    "BALKRISIND.NS": ("Balkrishna Industries", "Auto"),
    "APOLLOTYRE.NS": ("Apollo Tyres", "Auto"),
    "EXIDEIND.NS": ("Exide Industries", "Auto"),
    "ARE&M.NS": ("Amara Raja Energy & Mobility", "Auto"),

    # Services
    "INDIGO.NS": ("IndiGo (InterGlobe Aviation)", "Services"),
    "IRCTC.NS": ("IRCTC", "Services"),
    "CONCOR.NS": ("Container Corporation of India", "Services"),
    "ADANIPORTS.NS": ("Adani Ports", "Services"),
    "DELHIVERY.NS": ("Delhivery", "Services"),
    "BLUEDART.NS": ("Blue Dart Express", "Services"),
    "GMRAIRPORT.NS": ("GMR Airports", "Services"),
    "RVNL.NS": ("Rail Vikas Nigam", "Services"),
    "IRCON.NS": ("Ircon International", "Services"),
    "NBCC.NS": ("NBCC India", "Services"),
    "NAUKRI.NS": ("Info Edge (Naukri)", "Services"),
    "INDIAMART.NS": ("IndiaMART", "Services"),
    "CAMS.NS": ("CAMS", "Services"),
    "INDHOTEL.NS": ("Indian Hotels (Taj)", "Services"),
    "EIHOTEL.NS": ("EIH (Oberoi Hotels)", "Services"),
    "EASEMYTRIP.NS": ("EaseMyTrip", "Services"),

    # Telecom & Media
    "BHARTIARTL.NS": ("Bharti Airtel", "Telecom & Media"),
    "IDEA.NS": ("Vodafone Idea", "Telecom & Media"),
    "INDUSTOWER.NS": ("Indus Towers", "Telecom & Media"),
    "TATACOMM.NS": ("Tata Communications", "Telecom & Media"),
    "HFCL.NS": ("HFCL", "Telecom & Media"),
    "TEJASNET.NS": ("Tejas Networks", "Telecom & Media"),
    "ITI.NS": ("ITI Limited", "Telecom & Media"),
    "ZEEL.NS": ("Zee Entertainment", "Telecom & Media"),
    "SUNTV.NS": ("Sun TV Network", "Telecom & Media"),
    "PVRINOX.NS": ("PVR INOX", "Telecom & Media"),
    "NAZARA.NS": ("Nazara Technologies", "Telecom & Media"),
    "SAREGAMA.NS": ("Saregama India", "Telecom & Media"),

    # Real Estate
    "DLF.NS": ("DLF", "Real Estate"),
    "GODREJPROP.NS": ("Godrej Properties", "Real Estate"),
    "OBEROIRLTY.NS": ("Oberoi Realty", "Real Estate"),
    "PRESTIGE.NS": ("Prestige Estates", "Real Estate"),
    "PHOENIXLTD.NS": ("Phoenix Mills", "Real Estate"),
    "BRIGADE.NS": ("Brigade Enterprises", "Real Estate"),
    "SOBHA.NS": ("Sobha", "Real Estate"),
    "LODHA.NS": ("Lodha Developers", "Real Estate"),
    "SUNTECK.NS": ("Sunteck Realty", "Real Estate"),
    "ANANTRAJ.NS": ("Anant Raj", "Real Estate"),
    "NCC.NS": ("NCC Limited", "Real Estate"),
}

# rough descending order of household familiarity in India; used as the
# default ordering before live data arrives
POPULARITY = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "SBIN.NS", "ITC.NS", "BHARTIARTL.NS", "HINDUNILVR.NS", "LT.NS",
    "MARUTI.NS", "TMPV.NS", "TATASTEEL.NS", "AXISBANK.NS", "KOTAKBANK.NS",
    "BAJFINANCE.NS", "ASIANPAINT.NS", "TITAN.NS", "SUNPHARMA.NS", "M&M.NS",
    "WIPRO.NS", "HCLTECH.NS", "NESTLEIND.NS", "ULTRACEMCO.NS", "ONGC.NS",
    "NTPC.NS", "COALINDIA.NS", "POWERGRID.NS", "ADANIENT.NS", "ADANIPORTS.NS",
    "DMART.NS", "ETERNAL.NS", "PAYTM.NS", "IRCTC.NS", "INDIGO.NS",
    "TATAPOWER.NS", "TMCV.NS", "JIOFIN.NS", "LICI.NS", "HAL.NS",
    "BEL.NS", "DLF.NS", "VEDL.NS", "JSWSTEEL.NS", "HINDALCO.NS",
    "BAJAJ-AUTO.NS", "HEROMOTOCO.NS", "EICHERMOT.NS", "TVSMOTOR.NS", "IOC.NS",
    "BPCL.NS", "GAIL.NS", "TECHM.NS", "TRENT.NS", "PIDILITIND.NS",
    "BRITANNIA.NS", "DABUR.NS", "HAVELLS.NS", "MRF.NS", "BOSCHLTD.NS",
    "SWIGGY.NS", "NYKAA.NS", "PNB.NS", "BANKBARODA.NS", "CANBK.NS",
    "YESBANK.NS", "BAJAJFINSV.NS", "SBILIFE.NS", "HDFCLIFE.NS", "SBICARD.NS",
    "GRASIM.NS", "SAIL.NS", "CIPLA.NS", "DRREDDY.NS", "APOLLOHOSP.NS",
    "DIVISLAB.NS", "TATACONSUM.NS", "MARICO.NS", "GODREJCP.NS",
    "COLPAL.NS", "VBL.NS", "UNITDSPR.NS", "UBL.NS", "JUBLFOOD.NS",
    "PAGEIND.NS", "BATAINDIA.NS", "VOLTAS.NS", "BERGEPAINT.NS", "KALYANKJIL.NS",
    "ASHOKLEY.NS", "ESCORTS.NS", "HYUNDAI.NS", "OLAELEC.NS", "EXIDEIND.NS",
    "APOLLOTYRE.NS", "BALKRISIND.NS", "BHARATFORG.NS", "MOTHERSON.NS", "ARE&M.NS",
    "SUZLON.NS", "ADANIPOWER.NS", "ADANIGREEN.NS", "ADANIENSOL.NS", "JSWENERGY.NS",
    "NHPC.NS", "BHEL.NS", "SIEMENS.NS", "ABB.NS", "CGPOWER.NS",
    "POLYCAB.NS", "HINDPETRO.NS", "PETRONET.NS", "IGL.NS", "INDUSINDBK.NS",
    "IDFCFIRSTB.NS", "FEDERALBNK.NS", "AUBANK.NS", "SHRIRAMFIN.NS", "CHOLAFIN.NS",
    "MUTHOOTFIN.NS", "PFC.NS", "RECLTD.NS", "IRFC.NS", "HDFCAMC.NS",
    "LUPIN.NS", "BIOCON.NS", "AUROPHARMA.NS", "ZYDUSLIFE.NS", "TORNTPHARM.NS",
    "ALKEM.NS", "GLENMARK.NS", "MANKIND.NS", "ABBOTINDIA.NS", "IPCALAB.NS",
    "LAURUSLABS.NS", "FORTIS.NS", "MAXHEALTH.NS", "SYNGENE.NS", "LALPATHLAB.NS",
    "NMDC.NS", "HINDZINC.NS", "NATIONALUM.NS", "JINDALSTEL.NS", "APLAPOLLO.NS",
    "SHREECEM.NS", "AMBUJACEM.NS", "ACC.NS", "DALBHARAT.NS", "JKCEMENT.NS",
    "UPL.NS", "PIIND.NS", "SRF.NS", "TATACHEM.NS", "ASTRAL.NS",
    "PERSISTENT.NS", "COFORGE.NS", "MPHASIS.NS", "LTTS.NS", "OFSS.NS",
    "TATAELXSI.NS", "TATATECH.NS", "KPITTECH.NS", "CYIENT.NS", "BSOFT.NS",
    "CONCOR.NS", "DELHIVERY.NS", "BLUEDART.NS", "GMRAIRPORT.NS", "RVNL.NS",
    "IRCON.NS", "NBCC.NS", "NAUKRI.NS", "INDIAMART.NS", "CAMS.NS",
    "INDHOTEL.NS", "EIHOTEL.NS", "EASEMYTRIP.NS", "IDEA.NS", "INDUSTOWER.NS",
    "TATACOMM.NS", "HFCL.NS", "TEJASNET.NS", "ITI.NS", "ZEEL.NS",
    "SUNTV.NS", "PVRINOX.NS", "NAZARA.NS", "SAREGAMA.NS", "GODREJPROP.NS",
    "OBEROIRLTY.NS", "PRESTIGE.NS", "PHOENIXLTD.NS", "BRIGADE.NS", "SOBHA.NS",
    "LODHA.NS", "SUNTECK.NS", "ANANTRAJ.NS", "NCC.NS",
]
